# Generated by Django 2.0.6 on 2019-05-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('risk_id', models.AutoField(primary_key=True, serialize=False)),
                ('risk_name', models.CharField(max_length=255)),
            ],
        ),
    ]
