# Generated by Django 2.0.6 on 2019-05-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fieldtype',
            fields=[
                ('fieldtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('fieldtype_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_uid', models.AutoField(primary_key=True, serialize=False)),
                ('post_value', models.CharField(max_length=255)),
                ('post_form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('risk_id', models.AutoField(primary_key=True, serialize=False)),
                ('risk_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='field_fieldtype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Fieldtype'),
        ),
        migrations.AddField(
            model_name='field',
            name='field_risk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Risk'),
        ),
    ]
