# Generated by Django 2.0.6 on 2019-05-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fieldtype',
            fields=[
                ('fieldtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('fieldtype_name', models.CharField(max_length=255)),
            ],
        ),
    ]
