# Generated by Django 2.0.6 on 2019-05-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_value',
            new_name='p_val',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_form_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
    ]
