# Generated by Django 2.0.6 on 2019-05-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_auto_20190527_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='p_val',
            new_name='post_val',
        ),
    ]
