# Generated by Django 2.0.6 on 2019-06-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_auto_20190527_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
