# Generated by Django 2.0.6 on 2019-06-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0006_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_uid', models.AutoField(primary_key=True, serialize=False)),
                ('post_value', models.CharField(max_length=255)),
            ],
        ),
    ]
