# Generated by Django 2.0.6 on 2019-06-24 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_field_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='risk.Field'),
        ),
    ]
